# Generated by Django 2.1.5 on 2020-02-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_dish_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cost',
            field=models.CharField(max_length=128),
        ),
    ]
